CREATE TABLE ASPH_ASG_PROCESSED_DATA (
id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
filename_id NUMBER NOT NULL,
captured_instance VARCHAR2(20 BYTE) NOT NULL,
asg_no NUMBER(3,0) NOT NULL,
placement NUMBER(3,0) NOT NULL,
cal_coeff REAL NOT NULL,
rated_output NUMBER(6,0) NOT NULL,
extrema VARCHAR2(7 BYTE) NOT NULL, 
seconds_elapsed REAL NOT NULL,
processed_datapoint_microstrain REAL NOT NULL,
PRIMARY KEY(id),
constraint asph_asg_enumerate_extrema CHECK (extrema in ('maxima', 'minima')),
constraint asph_asg_fk_field_filename foreign key (filename_id) references ASPH_SENSOR_FILE_INFO (ID)
);
