CREATE TABLE ASPH_CSG_PROCESSED_DATA (
id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
filename_id NUMBER NOT NULL,
captured_instance VARCHAR2(20 BYTE) NOT NULL,
csg_no NUMBER(3,0) NOT NULL,
placement NUMBER(3,0) NOT NULL,
lin_gage_fctr REAL NOT NULL,
poly_gage_fctr_a REAL NOT NULL,
poly_gage_fctr_b REAL NOT NULL,
extrema VARCHAR2(7 BYTE) NOT NULL, 
seconds_elapsed REAL NOT NULL,
processed_datapoint_inches REAL NOT NULL,
PRIMARY KEY(id),
constraint asph_csg_enumerate_extrema CHECK (extrema in ('maxima', 'minima')),
constraint asph_csg_fk_field_filename foreign key (filename_id) references ASPH_SENSOR_FILE_INFO (ID)
);
