CREATE TABLE ASPH_LSR_PROF_PROCESSED_DATA (
id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
Day VARCHAR2(10 BYTE) NOT NULL,
Pass_Instance VARCHAR2(10 BYTE) NOT NULL,
filename_id NUMBER NOT NULL,
Sample_Number NUMBER(6,0) NOT NULL,
Horiz_mm_samp_no_1384_8088 REAL NOT NULL,
Laser_reading REAL NOT NULL,
Laserbeam_locn_mm NUMBER(6,0) NOT NULL,
Sampled_Time VARCHAR2(20 BYTE) NOT NULL,
PRIMARY KEY(id),
constraint asph_lsr_prof_fk_field_filename foreign key (filename_id) references ASPH_LSR_PROF_FILE_INFO (ID)
);
