CREATE TABLE ASPH_SENSOR_FILE_INFO (
id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
filename VARCHAR2(100 BYTE) NOT NULL,
day_no NUMBER(6,0) NOT NULL,
date_of_collection DATE NOT NULL,
operator VARCHAR2(30 BYTE) NOT NULL,
number_of_passes NUMBER(6,0) NOT NULL,
cumulative_number_of_passes NUMBER(10,0) NOT NULL,
room_temp_f NUMBER(4,0) NOT NULL,
pavement_temp_f NUMBER(4,0) NOT NULL,
input_axel_load NUMBER(6,0) NOT NULL,
measured_axel_load_lb NUMBER(6,0) NOT NULL,
plug_in_axel_load_kips FLOAT(10) NOT NULL,
run_number NUMBER(5,0) NOT NULL,
NOTES varchar2(200 BYTE),
PRIMARY KEY(id)
);
