CREATE TABLE ASPH_LSR_PROF_FILE_INFO (
id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
filename VARCHAR2(100 BYTE) NOT NULL,
Order_of_Scan  VARCHAR2(10 BYTE) NOT NULL,  /*PL1, PL2, ..., PL11 */
Starting_Timestamp  VARCHAR2(20 BYTE) NOT NULL,
Ending_Timestamp VARCHAR2(20 BYTE) NOT NULL,
Laser_beam_offset_mm FLOAT(4) NOT NULL, /* 2 bit precision floating point; precision = (4*0.30103) = 2 */
Laser_beam_offset_locn VARCHAR2(100 BYTE) NOT NULL,
Laser_beam_vertical_meas_Low_limit_mm FLOAT(7) NOT NULL, /* 3 bit precision floating point */
Laser_beam_vertical_meas_High_limit_mm FLOAT(7) NOT NULL,
Laser_beam_vertical_meas_range_mm FLOAT(7) NOT NULL,
Carriage_Start_Position_mm NUMBER(6,0) NOT NULL, /*precision 6, scale 0, i.e. total 6 digits, 0 digits after decimal point*/
Carriage_End_Position_mm NUMBER(6,0) NOT NULL,
Axle_Pos_E_W_mm NUMBER(6,0) NOT NULL,
Laser_Start_Position_mm NUMBER(6,0) NOT NULL,
Notes VARCHAR2(200 BYTE) NULL,
PRIMARY KEY(id)
);
