CREATE TABLE ASPH_THERMO_PROCESSED_DATA (
id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
filename_id NUMBER NOT NULL,
captured_instance VARCHAR2(20 BYTE) NOT NULL,
thermocouple_no NUMBER(3,0) NOT NULL,
extrema VARCHAR2(7 BYTE) NOT NULL, 
seconds_elapsed REAL NOT NULL,
processed_datapoint_f REAL NOT NULL,
PRIMARY KEY(id),
constraint asph_th_enumerate_extrema CHECK (extrema in ('maxima', 'minima')),
constraint asph_th_fk_field_filename foreign key (filename_id) references ASPH_SENSOR_FILE_INFO (ID)
);