CREATE TABLE ASPH_PC_PROCESSED_DATA (
id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
filename_id NUMBER NOT NULL,
captured_instance VARCHAR2(20 BYTE) NOT NULL,
pc_no NUMBER(3,0) NOT NULL,
lin_gage_fctr REAL NOT NULL,
poly_gage_fctr_a REAL NOT NULL,
poly_gage_fctr_b REAL NOT NULL,
poly_gage_fctr_c REAL NOT NULL,
extrema VARCHAR2(7 BYTE) NOT NULL, 
seconds_elapsed REAL NOT NULL,
processed_datapoint_kpa REAL NOT NULL,
PRIMARY KEY(id),
constraint asph_pc_enumerate_extrema CHECK (extrema in ('maxima', 'minima')),
constraint asph_pc_fk_field_filename foreign key (filename_id) references ASPH_SENSOR_FILE_INFO (ID)
);
