CREATE TABLE CONCRETE_STATIC_THERMO_PROCESSED_DATA (
id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
filename_id NUMBER NOT NULL,
thermo_no NUMBER(3,0) NOT NULL,
extrema VARCHAR2(7 BYTE) NOT NULL,
seconds_elapsed REAL NOT NULL,
processed_datapoint_F REAL NOT NULL,
constraint conc_stc_thm_fk_field_filename foreign key (filename_id) references CONCRETE_STATIC_SENSOR_FILE_INFO (ID)
);
