CREATE TABLE CONCRETE_STATIC_CSG_PROCESSED_DATA (
id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
filename_id NUMBER NOT NULL,
csg_no NUMBER(3,0) NOT NULL,
placement NUMBER(3,0) NOT NULL,
lin_gage_fctr REAL NOT NULL,
poly_gage_fctr_a REAL NOT NULL,
poly_gage_fctr_b REAL NOT NULL,
extrema VARCHAR2(7 BYTE) NOT NULL,
seconds_elapsed REAL NOT NULL,
processed_datapoint_inches REAL NOT NULL,
constraint conc_stc_csg_fk_field_filename foreign key (filename_id) references CONCRETE_STATIC_SENSOR_FILE_INFO (ID)
);
